server:
  port: 9166
spring:
  ai:
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        initialize-schema: true
        embeddingDimension: 1024
        indexType: IVF_FLAT
        metricType: COSINE
    openai:
      api-key:
      embedding:
        base-url:
        options:
          model:
          dimensions: 1024
